# Generated by Django 5.0.7 on 2024-08-10 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(default='Changeme@123', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Klass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('AIML', 'AIML'), ('AIDS', 'AIDS'), ('IT', 'IT'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL')], max_length=10)),
                ('section', models.CharField(max_length=1)),
            ],
            options={
                'unique_together': {('year', 'department', 'section')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(default='Changeme@123', max_length=255)),
                ('category', models.PositiveSmallIntegerField(choices=[(0, 'Common'), (1, 'Weak Learner'), (2, 'Average'), (3, 'Good'), (4, 'Topper')], default=0)),
                ('klass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_manager.klass')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manager.klass')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manager.staff')),
            ],
            options={
                'unique_together': {('code', 'klass')},
            },
        ),
    ]
