# Generated by Django 5.0.7 on 2024-08-10 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='materials/')),
                ('name', models.CharField(max_length=255)),
                ('category', models.PositiveSmallIntegerField(choices=[(0, 'Common'), (1, 'Weak Learner'), (2, 'Average'), (3, 'Good'), (4, 'Topper')])),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_manager.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(2, 'Late'), (1, 'Present'), (0, 'Absent')])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manager.student')),
            ],
            options={
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(choices=[('CAT 1', 'CAT 1'), ('CAT 2', 'CAT 2'), ('CAT 3', 'CAT 3'), ('SEM', 'SEM')], max_length=10)),
                ('secured', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manager.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manager.subject')),
            ],
            options={
                'unique_together': {('student', 'subject', 'exam')},
            },
        ),
    ]
