# Generated by Django 5.0.7 on 2024-08-10 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_manager', '0001_initial'),
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='klass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_manager.klass'),
        ),
    ]
