# Generated by Django 5.0.7 on 2024-08-10 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_manager', '0003_remove_attendance_klass_attendance_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='time',
        ),
    ]
