# Generated by Django 5.0.7 on 2024-08-10 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_manager', '0004_remove_attendance_time'),
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date', 'subject')},
        ),
    ]
