# Generated by Django 5.0.7 on 2024-08-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_manager', '0006_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='total',
            field=models.PositiveSmallIntegerField(blank=True, default=100, null=True),
        ),
    ]
